api_platform:
  extra_properties:
    standard_put: true
  title: Ambulance API
  version: 1.0.0
  description: 'API выездной службы'
  show_webby: false
  swagger:
    api_keys:
      JWT:
        name: Authorization
        type: header
  defaults:
    normalization_context:
      skip_null_values: false